import Link from "next/link";

export const metadata = {
  title: "Terms of Service — Siira",
  description: "The terms for using Siira.",
};

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mb-6">
      <h2
        className="text-base font-bold text-[#1C1917] mb-1.5"
        style={{ fontFamily: "'Plus Jakarta Sans', sans-serif" }}
      >
        {title}
      </h2>
      <div className="text-sm text-[#78716C] leading-relaxed space-y-2">{children}</div>
    </section>
  );
}

export default function TermsPage() {
  return (
    <div className="min-h-dvh bg-[#FDFBF7] flex flex-col">
      <div className="w-full max-w-xl mx-auto flex-1 flex flex-col px-5 py-6">
        <Link
          href="/"
          className="inline-flex items-center gap-2 text-[13px] font-semibold text-[#F97316] mb-5 min-h-[44px]"
        >
          ← Back
        </Link>
        <h1
          className="text-2xl font-bold text-[#1C1917] mb-1"
          style={{ fontFamily: "'Plus Jakarta Sans', sans-serif" }}
        >
          Terms of Service
        </h1>
        <p className="text-[12px] text-[#A8A29E] mb-6">Last updated: September 2026</p>

        <Section title="The service">
          <p>
            Siira is a speech-first language companion that helps you practice
            Mandarin Chinese and German through conversation, quizzes, and spaced
            review. The service is currently a prototype and may change over time.
          </p>
        </Section>

        <Section title="Your account">
          <p>
            You sign in with your email address via a magic link. You are
            responsible for keeping access to your email secure and for activity
            under your account.
          </p>
        </Section>

        <Section title="Acceptable use">
          <p>
            Use Siira for personal language learning. Do not abuse, disrupt, or
            attempt to break the service, scrape content at scale, or use outputs
            in ways that violate the law or anyone&apos;s rights.
          </p>
        </Section>

        <Section title="AI-generated content">
          <p>
            Lessons, corrections, quizzes, and themes are generated by AI and may
            contain mistakes. They are learning aids, not certified instruction —
            always double-check anything important.
          </p>
        </Section>

        <Section title="Availability">
          <p>
            We aim to keep Siira running smoothly but do not guarantee
            uninterrupted availability. Features may be added, changed, or removed
            as the product evolves.
          </p>
        </Section>

        <Section title="Termination">
          <p>
            You may stop using Siira at any time. We may suspend accounts that
            violate these terms. Our privacy policy explains how your data is
            handled, including deletion on request.
          </p>
        </Section>

        <Section title="Contact">
          <p>
            Questions about these terms? Reach us at{" "}
            <span className="font-semibold text-[#1C1917]">support@siira.chat</span>.
          </p>
        </Section>
      </div>
    </div>
  );
}
